### ISSUE TITLE
Swagger: Failed to load API definition

### ISSUE THREAD

**Issue by nejci** [Blarc/igralni-streznik#9]
After launching the server and navigating to http://localhost:8088, we get warning "Failed to load API definition. Fetch error
INTERNAL SERVER ERROR /swagger.json" 

Log:
```
127.0.0.1 - - [2023-05-05 14:21:53] "GET /swaggerui/swagger-ui.css HTTP/1.1" 304 191 0.029998
Unable to render schema
Traceback (most recent call last):
  File "D:\Nejc\sluzba\LASPP\poucevanje\Robo liga FRI\2023\koda\streznik\venv\Lib\site-packages\flask_restx\api.py", line 573, in __schema__
    self._schema = Swagger(self).as_dict()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nejc\sluzba\LASPP\poucevanje\Robo liga FRI\2023\koda\streznik\venv\Lib\site-packages\flask_restx\swagger.py", line 304, in as_dict
    "definitions": self.serialize_definitions() or None,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Nejc\sluzba\LASPP\poucevanje\Robo liga FRI\2023\koda\streznik\venv\Lib\site-packages\flask_restx\swagger.py", line 659, in serialize_definitions       
    return dict(
           ^^^^^
  File "D:\Nejc\sluzba\LASPP\poucevanje\Robo liga FRI\2023\koda\streznik\venv\Lib\site-packages\flask_restx\swagger.py", line 660, in <genexpr>
    (name, model.__schema__) for name, model in self._registered_models.items()  
           ^^^^^^^^^^^^^^^^
  File "D:\Nejc\sluzba\LASPP\poucevanje\Robo liga FRI\2023\koda\streznik\venv\Lib\site-packages\flask_restx\model.py", line 68, in __schema__
    schema = self._schema
             ^^^^^^^^^^^^
  File "D:\Nejc\sluzba\LASPP\poucevanje\Robo liga FRI\2023\koda\streznik\venv\Lib\site-packages\flask_restx\model.py", line 151, in _schema
    properties[name] = field.__schema__
                       ^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute '__schema__'
```

**Comment by Blarc** [comment]
I made a copy paste mistake. Fixed by https://github.com/Blarc/igralni-streznik/commit/fb46fd69c2db0e64afd77e6d1a26946b595a5eb8.
